### ISSUE TITLE
Minimap does not save

### ISSUE THREAD

**Issue by Frowsty** [OTCv8/otclientv8#23]
The newest update of the client (2.2) has created and issue where the minimap either does not save correctly or load correctly thus causing the client to not load the map at all.

**Comment by OTCv8** [comment]
Fixed

**Comment by dravenvip** [comment]
Still not fixed when use multi client if gonna black agian :/
